fix: file name formatting by white space
wswebcreation/multiple-cucumber-html-reporter pull request #148
Opened 2021-08-05 07:13 UTC by Seunghyum

first of all Thank you for make nice package. 
this PR is for fix .html file name formatting by white place.
my mother tongue is Korean. i want to make html file by Korean

if feature is `로그인 테스트` it is become `------.html` file.
i want to fix this.

2021-08-10 08:56 UTC, kontownik approved these changes

2021-08-10 08:57 UTC, kontownik commented
wow that's simple solution :) thanks @Seunghyum

2021-08-16 11:23 UTC, wswebcreation requested changes

2021-08-16 11:23 UTC, wswebcreation commented on lib/generate-report.js
> +			feature.id = `${ idPrefix }${ feature.id }`.split(" ").join("-");
Thanks for the PR @Seunghyum 

Sorry for the late reply, i was on vacation. You're fix breaks that fact that strange chars are now allowed again, the previous one didn't allow chars that were not alphanumeric. 

Maybe do something like this
```js
feature.id = `${ idPrefix }${ feature.id }`.split(" ").join("-").replace(/[^a-zA-Z0-9-_]/g, '-');
```

2021-11-26 14:53 UTC, wswebcreation commented
Closing this due to inactivity

2021-11-26 14:53 UTC, closed without merging