Dark theme support
wswebcreation/multiple-cucumber-html-reporter pull request #182
Opened 2022-05-23 16:59 UTC by Baskercarrer

* BG Colors are applied thought element level. 

_Note: I know it is not a professional way. Please feel free to decline it if not suits._

2022-05-24 18:43 UTC, Baskercarrer commented
thanks for the suggestion

2022-05-24 19:24 UTC, BaCaRoZzo commented
@Baskercarrer not sure if it works on the title but it surely works in [the body of the message](https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/182#issue-1245462719). So you should add it there. :+1:

2022-05-26 06:50 UTC, wswebcreation requested changes
Wow @Baskercarrer 

This looks really awesome, thanks for all the effort, some small requests

Can you adjust the selectbox to this
![image](https://user-images.githubusercontent.com/11979740/170430542-be3ed132-b42d-4322-93a5-2720d3186f63.png)
with this code for darkmode
```css
div.dataTables_wrapper div.dataTables_length select {
    width: 75px;
    display: inline-block;
    background: #3b3b3b;
    border-color: #858585;
    color: #eee;
}
```

Same for the search box
![image](https://user-images.githubusercontent.com/11979740/170430870-3a048a31-ed2c-44f0-bc4a-96eaf901dbdf.png)
```css
div.dataTables_wrapper div.dataTables_filter input {
    margin-left: 0.5em;
    display: inline-block;
    width: auto;
    background: #3b3b3b;
    border-color: #858585;
    color: #eee;
}
```

Can you also change the table a bit more into darkish mode?
Something like this

![image](https://user-images.githubusercontent.com/11979740/170432443-3456eb85-6fea-44d3-b9e5-1e7e8b7e2970.png)

where the table header background is `#`3b3b3b` and all blue colors are `#eee`?

The we only have the pager left, here's an example
![image](https://user-images.githubusercontent.com/11979740/170433440-75e2cdb1-2ca9-451f-9d36-f5a2766098d9.png)

But maybe you have a better idea about this

Then when I look at the feature pages I see this
![image](https://user-images.githubusercontent.com/11979740/170433657-57f2ac5e-85ec-49c0-97d5-8350954b4fbb.png)

I'm not sure what the issue is here, but it looks like the body doesn't have the right darkmode. Can you also check the colors there?

Again, thanks for all your hard work on this

2022-05-26 10:45 UTC, Baskercarrer commented
@wswebcreation - made a commit as per your suggestion. Could you please check one time?
Note: Table header color is chosen by myself and am happy to get color code if you are have something else to add. 
* Now colors are applied by CSS not by JS. Hope it will be faster than before i believe.

2022-05-26 15:24 UTC, wswebcreation requested changes
Thanks man, just a few small last comments

Can you remove the hover effect for darkmode on the chevrons?
![image](https://user-images.githubusercontent.com/11979740/170519090-f649e0bd-040a-4fa5-96b0-9eda92ec76d8.png)
```css
.darkmode .panel_toolbox > li > a:hover {
   background: transparent;
}
```

and change this button, on the feature page, to a color that is more in line with the rest?
![image](https://user-images.githubusercontent.com/11979740/170520003-a1ad8f9d-2a0f-4ff0-9ee9-5e9f1a171f3b.png)


something like this
![image](https://user-images.githubusercontent.com/11979740/170519868-d9b3a2ee-efae-4672-9791-6b57156162a4.png)
```css
.darkmode .btn-info {
    color: #eee; 
    background-color: #337ab7;
    border-color: #337ab7;
}
```

If you agree and can push them then I can also merge it and release a new version

2022-05-26 15:24 UTC, wswebcreation commented on templates/style.css
> +
Maybe remove this extra line break
```suggestion
```

2022-05-26 16:04 UTC, Baskercarrer commented
its my bad to not noticing such things. Anyway am done.

2022-05-26 16:12 UTC, wswebcreation approved these changes
LGTM now, thanks for all your work here!

2022-05-26 16:12 UTC, merged